// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error('Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
}

// Create the supabase client with enhanced configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'TEJAS'
    }
  }
});

// Helper types for better type safety
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Helper functions for common operations
export const supabaseHelpers = {
  // Get current user with error handling
  getCurrentUser: async () => {
    try {
      const { data: { user }, error } = await supabase.auth.getUser();
      if (error) throw error;
      return user;
    } catch (error) {
      console.error('Error getting current user:', error);
      return null;
    }
  },

  // Get user profile
  getUserProfile: async (userId?: string) => {
    try {
      const currentUser = userId || (await supabaseHelpers.getCurrentUser())?.id;
      if (!currentUser) return null;

      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', currentUser)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error getting user profile:', error);
      return null;
    }
  },

  // Check if user is authenticated
  isAuthenticated: async () => {
    const user = await supabaseHelpers.getCurrentUser();
    return !!user;
  },

  // Sign out with cleanup
  signOut: async () => {
    try {
      const { error } = await supabase.auth.signOut();
      if (error) throw error;
      
      // Clear any local storage if needed
      localStorage.removeItem('current_session_id');
      
      return true;
    } catch (error) {
      console.error('Error signing out:', error);
      return false;
    }
  }
};

// Add this to your supabase client file or create a separate helper file

export const createUserProfile = async (user: any, userData?: any) => {
  try {
    // Check if profile already exists
    const { data: existingProfile } = await supabase
      .from('profiles')
      .select('id')
      .eq('id', user.id)
      .single();

    if (!existingProfile) {
      // Create profile manually
      const { error } = await supabase
        .from('profiles')
        .insert({
          id: user.id,
          email: user.email,
          full_name: userData?.full_name || user.user_metadata?.full_name || user.email.split('@')[0],
          user_type: userData?.user_type || 'teacher'
        });

      if (error) throw error;
    }

    return { success: true };
  } catch (error) {
    console.error('Error creating profile:', error);
    return { success: false, error };
  }
};

// Use this in your authentication flow
const handleSignUp = async (email: string, password: string, userData: any) => {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: userData
    }
  });

  if (error) throw error;

  // Manually create profile if auth trigger didn't work
  if (data.user) {
    await createUserProfile(data.user, userData);
  }

  return { data, error };
};


// Export commonly used table types
export type Profile = Tables<'profiles'>;
export type Course = Tables<'courses'>;
export type Attendance = Tables<'attendance'>;
export type Note = Tables<'notes'>;
export type Task = Tables<'tasks'>;
export type Grade = Tables<'grades'>;
export type Enrollment = Tables<'enrollments'>;
export type StudySession = Tables<'study_sessions'>;
export type UserTimetable = Tables<'user_timetables'>;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
